config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/logout' => 'devise/sessions#destroy'

    get '/login' => 'devise/sessions#new'
  end
  
  root 'pages#dashboard'

  get '/feed', to: 'pages#feed'
  get '/geral', to: 'pages#geral'  
  get '/pessoas', to: 'pages#pessoas'

  get '/user/add_new_follower' => 'users#add_new_follower', :as => :add_new_follower
  get '/user/remote_follower' => 'users#remote_follower', :as => :remote_follower

  get '/increment_deslike_geral' => 'publications#increment_deslike_geral', :as => :increment_deslike_g
  get '/increment_like_geral' => 'publications#increment_like_geral', :as => :increment_like_g
  get '/increment_deslike_feed' => 'publications#increment_deslike_feed', :as => :increment_deslike_f
  get '/increment_like_feed' => 'publications#increment_like_feed', :as => :increment_like_f

  resources :reports
  resources :notices
  resources :users
  resources :publications
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_one_attached :image
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
        
    @notices = Notice.all
  end

  def show
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end    
  end

  def new
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @notice = Notice.new
  end

  def edit
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end    
  end

  def create
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_notice
      @notice = Notice.find(params[:id])
    end

    def notice_params
      params.require(:notice).permit(:title, :description, :url, :image)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_with(model: notice, local: true, html: {class:"ui fluid form" }) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
        <% notice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui divider"></div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar notice', :class => 'ui blue button' %>
  </div>

  <div class="ui divider"></div>

<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.title %></td>
        <td><%= notice.description %></td>
        <td><%= notice.url %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @notice.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @notice.url %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>