config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/logout' => 'devise/sessions#destroy'

    get '/login' => 'devise/sessions#new'
  end
  
  root 'pages#dashboard'

  get '/feed', to: 'pages#feed'
  get '/geral', to: 'pages#geral'  
  get '/pessoas', to: 'pages#pessoas'

  get '/user/add_new_follower' => 'users#add_new_follower', :as => :add_new_follower
  get '/user/remote_follower' => 'users#remote_follower', :as => :remote_follower

  get '/increment_deslike_geral' => 'publications#increment_deslike_geral', :as => :increment_deslike_g
  get '/increment_like_geral' => 'publications#increment_like_geral', :as => :increment_like_g
  get '/increment_deslike_feed' => 'publications#increment_deslike_feed', :as => :increment_deslike_f
  get '/increment_like_feed' => 'publications#increment_like_feed', :as => :increment_like_f

  resources :reports
  resources :notices
  resources :users
  resources :publications
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_one_attached :image
  after_initialize :init
  
  belongs_to :user
  belongs_to :category

  def init
    self.like  ||= 0
    self.deslike ||= 0
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  def increment_like_geral
    @publication = Publication.all.find(params[:publication_like])

    @publication.like = @publication.like+1

    @publication.save

    redirect_to geral_path
  end

  def increment_deslike_geral
    @publication = Publication.all.find(params[:publication_deslike])

    @publication.deslike = @publication.deslike-1

    @publication.save

    redirect_to geral_path
  end

  def increment_like_feed
    @publication = Publication.all.find(params[:publication_like])

    @publication.like = @publication.like+1

    @publication.save

    redirect_to feed_path
  end

  def increment_deslike_feed
    @publication = Publication.all.find(params[:publication_deslike])

    @publication.deslike = @publication.deslike-1

    @publication.save

    redirect_to feed_path
  end

  def index
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @publications = Publication.all
  end

  def show
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
  end

  def new
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @users_admin = User.all.select { |u| u.admin == true }
    
    @categories = Category.all
    @publication = Publication.new
  end

  def edit
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
  end

  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id

    respond_to do |format|
      if @publication.save
        format.html { redirect_to feed_path, notice: 'Seu tópico foi criado com sucesso' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { redirect_to feed_path, alert: 'Seu tópico não foi criado com sucesso porque a categoria seleciona não existe' }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
        
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to feed_path, notice: 'Sua publicação foi deletada com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    def set_publication
      @publication = Publication.find(params[:id])
    end

    def publication_params
      params.require(:publication).permit(:image, :title, :description, :category_id, :user_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true, html: {class:"ui fluid form" }) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :Categoria %>
    <%= collection_select(:publication, :category_id, @categories, :id, :name, {:prompt => true, :multiple=>true }) %>
  </div>

  <div class="field">
    <%= form.label :Usuário %>
    <%= collection_select(:publication, :user_id, @users_admin, :id, :name, {:prompt => true, :multiple=>true }) %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', :class => 'ui blue button' %>
  </div>

  <div class="ui divider"></div>

<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publications</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Categoria</th>
      <th>Usuário</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.title %></td>
        <td><%= publication.description %></td>
        <td><%= publication.category.name %></td>
        <td><%= publication.user.name %></td>

        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @publication.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @publication.category_id %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>