config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/logout' => 'devise/sessions#destroy'

    get '/login' => 'devise/sessions#new'
  end
  
  root 'pages#dashboard'

  get '/feed', to: 'pages#feed'
  get '/geral', to: 'pages#geral'  
  get '/pessoas', to: 'pages#pessoas'

  get '/user/add_new_follower' => 'users#add_new_follower', :as => :add_new_follower
  get '/user/remote_follower' => 'users#remote_follower', :as => :remote_follower

  get '/increment_deslike_geral' => 'publications#increment_deslike_geral', :as => :increment_deslike_g
  get '/increment_like_geral' => 'publications#increment_like_geral', :as => :increment_like_g
  get '/increment_deslike_feed' => 'publications#increment_deslike_feed', :as => :increment_deslike_f
  get '/increment_like_feed' => 'publications#increment_like_feed', :as => :increment_like_f

  resources :reports
  resources :notices
  resources :users
  resources :publications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/motivation.rb
class Motivation < ApplicationRecord
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_one_attached :image
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_one_attached :image
  after_initialize :init
  
  belongs_to :user
  belongs_to :category

  def init
    self.like  ||= 0
    self.deslike ||= 0
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :motivation
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_many :users
  has_many :publications

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  def index
    @kinds = Kind.all
  end

  def show
  end

  def new
    @kind = Kind.new
  end

  def edit
  end

  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_kind
      @kind = Kind.find(params[:id])
    end

    def kind_params
      params.require(:kind).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    if user_signed_in?
      redirect_to feed_path
    end
  end

  def feed
    @feed = true

    @publication = Publication.new
    @categories = Category.all

    @publications_by_follow = []

    current_user.users.each do |u|
      u.publications.each do |p|
        @publications_by_follow << p
      end
    end

    current_user.publications.each do |p|
      @publications_by_follow << p
    end
  end

  def geral
    @geral = true

    @categories_names = []
    @categories = Category.all

    Category.all.each do |c|
      @categories_names << c.name
    end

    @publication_before_ransack = Publication.all

    @q = @publication_before_ransack.ransack(params[:q])
    @publications = @q.result.page(params[:page])
  end

  def pessoas
    @pessoas = true
    
    @user_follower = false
    
    @report = Report.new

    @q = User.all.ransack(params[:q])
    @users = @q.result.page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def add_new_follower
    redirect_to pessoas_path, notice: 'Você seguiu o usuário com sucesso' if current_user.users << User.all.select { |m| m.email == params[:user_email] }
  end

  def remote_follower
    redirect_to pessoas_path, notice: 'Você deixou de seguir o usuário especificado' if current_user.users.delete(User.all.select { |m| m.email == params[:user_email] })
  end

  def index
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @users = User.all
  end

  def show
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
  end

  def new
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @user = User.new
  end

  def edit
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
    
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :age, :description, :phone, :address, :admin, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pages/_menu_superior.html.erb
<div class="menu_superior">
  <p class="opina_livre">OPINA LIVRE</p>

  <div class="center">
    <% if user_signed_in? %>
      <a class="option_superior feed <%= 'selected' if @feed == true %>" href="/feed">Feed</a>
      <a class="option_superior geral <%= 'selected' if @geral == true %>" href="/geral">Geral</a>
      <a class="option_superior pessoas <%= 'selected' if @pessoas == true %>" href="/pessoas">Pessoas</a>    
    <% end %>
  </div>

  <div class="right">
    <% if user_signed_in? %>

      <div class="ui dropdown">
        <p><i class="user icon"></i></p>

        <div class="menu padding_top">
          <div class="dados_dropdown">
            <% if current_user.image.attached? %>
              <%= image_tag current_user.image, :size => "240x180" %>
            <% else %>
              <%= image_tag 'sem_foto', :size => "240x180" %>
            <% end %>

            <br class="item">

            <p class="item_dropdown name"><%= current_user.name %></p>
            <p class="item_dropdown email"><%= current_user.email %></p>        
          </div>

          <div class="ui divider"></div>

          <div class="buttons_dropdown">
            <%= link_to 'editar', edit_user_registration_path, :class => 'item_dropdown ui blue button' %>
            <%= link_to 'sair', destroy_user_session_path, :class => 'item_dropdown ui red button' %>            
          </div>

          <div class="ui divider"></div>

          <div class="view_follow">
            <p class="open_view_follow" onclick="$('.ui.modal.seguidores').modal('show');">Seguidores</p>
            <p class="open_view_follow" onclick="$('.ui.modal.seguindo').modal('show');">Seguindo</p>
          </div>

        </div>
      </div>

      <% if current_user.admin == true %>
        <div class="ui dropdown">
          <p><i class="paperclip icon"></i></p>

          <div class="menu">
            <div class="dados_dropdown">

              <br class="item">
      
              <p>Opções de administrador do site</p>

              <div class="ui divider"></div>

              <%= link_to notices_path do %>
                <p class="item_admin">Notícias</p>
              <% end %>

              <%= link_to publications_path do %>
                <p class="item_admin">Tópicos</p>
              <% end %>

              <%= link_to reports_path do %>
                <p class="item_admin">Reports</p>
              <% end %>

              <%= link_to users_path do %>
                <p class="item_admin">Usuários</p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

    <% else %>
      <%= link_to 'login', new_user_session_path, :class => 'text_devise_menu' %>
      <%= link_to 'registro', new_user_registration_path, :class => 'text_devise_menu' %>
    <% end %>

    <div class="ui modal users_modal seguindo">
      <i class="close icon" onclick="$('.ui.modal').modal('hide');"></i>

      <div class="header">Pessoas que você está seguindo no momento -> <%= current_user.users.count if user_signed_in? %></div>

      <div class="content flex_column height_max_modal">
        <% if user_signed_in? %>
          <% current_user.users.each do |u| %>
            <div class="flex_row">
              <% if u.image.attached? %>
                <%= image_tag u.image, :size => "160x100" %>
              <% else %>
                <%= image_tag 'sem_foto', :size => "160x100" %>
              <% end %>

              <div class="margin_left_15 flex_column">
                <p><strong>Nome: </strong><%= u.name %></p>
                <p><strong>E-mail: </strong><%= u.email %></p>

                <% if u.admin == true %>
                  <p><strong>Usuário</strong> administrador</p>
                <% else %>
                  <p><strong>Tipo de usuário:</strong> normal</p>
                <% end %>         
              </div>              
            </div>

            <div class="ui divider"></div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="ui modal users_modal seguidores">
      <i class="close icon" onclick="$('.ui.modal').modal('hide');"></i>

      <% if user_signed_in? %>
        <% followers = 0 %>

        <% User.all.each do |follower| %>
          <% follower.users.each do |follower_user| %>
            <% followers = followers+1 if follower_user.id == current_user.id %>
          <% end %>
        <% end %>

        <div class="header">Seus seguidores -> <%= followers %></div>

        <div class="content flex_column height_max_modal">
          <% User.all.each do |u| %>
            <% if u.users.include? current_user %>
              <div class="flex_row">
                <% if u.image.attached? %>
                  <%= image_tag u.image, :size => "160x100" %>
                <% else %>
                  <%= image_tag 'sem_foto', :size => "160x100" %>
                <% end %>

                <div class="margin_left_15 flex_column">
                  <p><strong>Nome: </strong><%= u.name %></p>
                  <p><strong>E-mail: </strong><%= u.email %></p>

                  <% if u.admin == true %>
                    <p><strong>Usuário</strong> administrador</p>
                  <% else %>
                    <p><strong>Tipo de usuário:</strong> normal</p>
                  <% end %>         
                </div>              
              </div>

              <div class="ui divider"></div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div> 

app/views/pages/feed.html.erb
<% content_for :title do %>
 - Publicações
<% end %>

<div class="main">
  <%= render 'menu_superior' %>

  <div class="ui container content">

    <div class="adicionar_nova_publicação separar_do_menu">
      <p>Todos os tópicos das pessoas que você está seguindo no momento.</p>
      <p class="title_novo_topico" onclick="$('.new_topico_modal').modal('show')"><strong>Novo tópico</strong></p>
    </div>

    <p>Adicione um novo tópico pra criar debates</p>

    <div class="ui divider"></div>

    <div class="ui modal new_topico_modal">
      <i class="close icon" onclick="$('.ui.modal').modal('hide');"></i>

      <div class="header">
        Nova publicação
      </div>

      <div class="content report_content_modal">
        <%= form_for @publication, html: {class:"ui fluid form" } do |f| %>

          <div class="double_select">
            <%= f.text_field :title, :placeholder => 'Título', :required => 'true' %>            
            <%= collection_select(:publication, :category_id, @categories, :id, :name, {:prompt => 'Escolha uma categoria', :multiple=>true }) %>
          </div>

          <div class="ui divider"></div>

          <%= f.text_area :description, :placeholder => 'Conteúdo', :required => 'true' %>

          <div class="ui divider"></div>

          <%= f.file_field :image, :prompt => 'Escolha uma categoria', class: 'cursor_on' %>

          <div class="ui divider"></div>

          <%= f.submit "Enviar tópico", :class => 'ui positive button' %>
        <% end %>
      </div>
    </div>

    <% if notice %>

      <div class="ui success message sucess_message">
        <div class="header">
          <i class="close icon" onclick="$('.sucess_message').hide()"></i>
          <%= notice %>
        </div>
      </div>

    <% end %>

    <% if alert %>

      <div class="ui error message error_message">
        <div class="header">
          <i class="close icon" onclick="$('.error_message').hide()"></i>
          <%= alert %>
        </div>
      </div>

    <% end %>

    <% if @publications_by_follow.count > 0 %>

      <% @publications_by_follow.each do |p| %>
        <div class="ui modal <%= p.id %>">
          <i class="close icon" onclick="$('.ui.modal.<%= p.id %>').modal('hide');"></i>

          <div class="header">
            Dados da publicação
          </div>

          <div class="content publication_content">

            <div class="publication_content_image">
              <% if p.image.attached? %>
                <%= image_tag p.image, :size => "240x180" %>
              <% else %>
                <%= image_tag 'sem_foto', :size => "240x180" %>
              <% end %>

              <div class="ui divider"></div>
            </div>

            <div class="publication_content_informations">
              <h1><%= p.title %></h1>

              <div class="ui divider"></div>

              <p>Categoria: <%= p.category.name %></p>

              <p>Criador: <%= p.user.name %></p>
              <p>E-mail: <%= p.user.email %></p>

              <div class="ui divider"></div>

              <div class="publication_content_description">
                <p><%= p.description %></p>                  
              </div>
            </div>

          </div>
        </div>

        <div class="publication_card">
          <div class="publication_card_image">
            <% if p.image.attached? %>
              <%= image_tag p.image, :size => "240x180" %>
            <% else %>
              <%= image_tag 'sem_foto', :size => "240x180" %>
            <% end %>
            <p>Categoria: <%= p.category.name %></p>
            <p>Criador: <%= p.user.name %></p>

            <% if p.user.email != current_user.email %>
              <div class="ui divider"></div>

              <div class="actions_line_deslike">
                <p>Likes: <%= p.like %> 
                  <%= link_to increment_like_f_path(publication_like: p) do %>
                    <i class="thumbs up icon like"></i>
                  <% end %>
                </p>
                <p>Deslikes: <%= p.deslike %> 
                  <%= link_to increment_deslike_f_path(publication_deslike: p) do %>
                    <i class="thumbs down icon deslike"></i>
                  <% end %>
                </p>                
              </div>
            <% end %>
          </div>

          <div class="publication_card_informations">
            <div class="title_and_icons">
              <h1 class="title"><%= p.title %></h1>

              <div class="icones_on_publications">
                <% if p.user.email == current_user.email %>
                  <%= link_to p, method: :delete, data: { confirm: 'Deseja realmente deletar seu tópico? :(' } do %>
                    <p><i class="trash icon"></i></p>
                  <% end %>
                <% else %>
                  <p><i></i></p>
                <% end %>

                <p><i class="expand arrows alternate icon" onclick="$('.ui.modal.<%= p.id %>').modal('show')"></i></p>
              </div>
            </div>
            <p class="description">Descrição: <%= p.description %></p>
          </div>
        </div>

        <div class="ui divider"></div>
      <% end %>
    <% else %>
      <h1>Ainda não há nada por aqui</h1>
      <div class="ui divider"></div>
    <% end %>

  </div>
</div>

app/views/pages/geral.html.erb
<% content_for :title do %>
 - Geral
<% end %>

<div class="main">
  <%= render 'menu_superior' %>

  <div class="ui container content">

    <p class="separar_do_menu">Todos os tópicos presentes no sistema com uma função de filtros integrada</p>

    <div class="ui divider"></div>

    <% if notice %>

      <div class="ui success message sucess_message">
        <div class="header">
          <i class="close icon" onclick="$('.sucess_message').hide()"></i>
          <%= notice %>
        </div>
      </div>

    <% end %>

    <% if alert %>

      <div class="ui error message error_message">
        <div class="header">
          <i class="close icon" onclick="$('.error_message').hide()"></i>
          <%= alert %>
        </div>
      </div>

    <% end %>

    <div class="all_publications_container">
      <% if @categories_names.count > 0 and @publications.count > 0 %>
        <div class="filtros_de_busca">
          <p class="title_search" onclick="$('.menu_filtros').toggle(); $('.caret.down.icon').toggle(); $('.caret.up.icon').toggleClass('hide');">Filtros para busca de tópicos<i class="caret down
       icon"></i><i class="caret up
       icon hide"></i></p>

          <div class="menu_filtros">
            <%= search_form_for @q, url: '/feed', html: { class: 'ui tinny form' } do |f| %>
              <div class="fields">
                <div class="three wide field">
                  <%= f.label :title %>
                  <%= f.search_field :title_cont, maxlength: 100  %>
                </div>

                <div class="three wide field">
                  <%= f.label :Usuário %>
                  <%= f.search_field :user_name_cont, maxlength: 100  %>
                </div>

                <div class="three wide field">
                  <%= f.label :categorias %>
                  <%= f.select :category_name_cont, @categories_names, :prompt => 'Categoria para busca' %>
                </div>
              </div>

              <br class="item">

              <div class="fields">
                <div class="field">
                  <%= link_to 'Limpar', feed_path, class: 'ui gray button' %>
                  <%= f.submit 'Pesquisar', class: "ui blue button" %>
                </div>
              </div>
            <% end %>          
          </div>
        </div>

        <div class="ui divider"></div>

        <% @publications.each do |p| %>

          <div class="ui modal <%= p.id %>">
            <i class="close icon" onclick="$('.ui.modal.<%= p.id %>').modal('hide');"></i>

            <div class="header">
              Dados da publicação
            </div>

            <div class="content publication_content">

              <div class="publication_content_image">
                <% if p.image.attached? %>
                  <%= image_tag p.image, :size => "240x180" %>
                <% else %>
                  <%= image_tag 'sem_foto', :size => "240x180" %>
                <% end %>

                <div class="ui divider"></div>
              </div>

              <div class="publication_content_informations">
                <h1><%= p.title %></h1>

                <div class="ui divider"></div>

                <p>Categoria: <%= p.category.name %></p>

                <p>Criador: <%= p.user.name %></p>
                <p>E-mail: <%= p.user.email %></p>

                <div class="ui divider"></div>

                <div class="publication_content_description">
                  <p><%= p.description %></p>                  
                </div>
              </div>

            </div>
          </div>

          <div class="publication_card">
            <div class="publication_card_image">
              <% if p.image.attached? %>
                <%= image_tag p.image, :size => "240x180" %>
              <% else %>
                <%= image_tag 'sem_foto', :size => "240x180" %>
              <% end %>
              <p>Categoria: <%= p.category.name %></p>
              <p>Criador: <%= p.user.name %></p>

              <% if p.user.email != current_user.email %>
                <div class="ui divider"></div>

                <div class="actions_line_deslike">
                  <p>Likes: <%= p.like %>  
                    <%= link_to increment_like_g_path(publication_like: p) do %>
                      <i class="thumbs up icon like"></i>
                    <% end %>
                  </p>

                  <p>Deslikes: <%= p.deslike %>  
                    <%= link_to increment_deslike_g_path(publication_deslike: p) do %>
                      <i class="thumbs down icon deslike"></i>
                    <% end %>
                  </p>                
                </div>
              <% end %>
            </div>

            <div class="publication_card_informations">
              <div class="title_and_icons">
                <h1 class="title"><%= p.title %></h1>

                <div class="icones_on_publications">
                  <% if p.user.email == current_user.email %>
                    <%= link_to p, method: :delete, data: { confirm: 'Deseja realmente deletar seu tópico? :(' } do %>
                      <p><i class="trash icon"></i></p>
                    <% end %>
                  <% else %>
                    <p><i></i></p>
                  <% end %>

                  <p><i class="expand arrows alternate icon" onclick="$('.ui.modal.<%= p.id %>').modal('show')"></i></p>
                </div>
              </div>
              <p class="description">Descrição: <%= p.description %></p>
            </div>
          </div>

          <div class="ui divider"></div>

        <% end %>
      <% else %>
        <h1>Ainda não há nada por aqui</h1>
        <div class="ui divider"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/pessoas.html.erb
<% content_for :title do %>
 - Usuários
<% end %>

<div class="main">
  <%= render 'menu_superior' %>

  <div class="ui container content">
    <div class="all_users_container">

      <p class="separar_do_menu">Listagem de todos os usuários do sistema. Siga novas pessoas para demonstrar mais interesse em seus tópicos. Obs.: você não aparece aqui!</p>

      <div class="ui divider"></div>

      <p class="red" onclick="$('.ui.modal.email_modal').modal('show');">Reportar um usuário <i class="exclamation triangle icon message_perfil"></i></p>

      <div class="ui divider"></div>

      <div class="filtros_de_busca">
        <p class="title_search" onclick="$('.menu_filtros').toggle(); $('.caret.down.icon').toggle(); $('.caret.up.icon').toggleClass('hide');">Filtros para busca de usuário<i class="caret down
 icon"></i><i class="caret up
       icon hide"></i></p>

        <div class="menu_filtros">
          <%= search_form_for @q, url: '/pessoas', html: { class: 'ui tinny form' } do |f| %>
            <div class="fields">
              <div class="three wide field">
                <%= f.label :nome %>
                <%= f.search_field :name_cont, maxlength: 100  %>
              </div>
              <div class="three wide field">
                <%= f.label :email %>
                <%= f.search_field :email_cont, maxlength: 100  %>
              </div>
            </div>

            <br class="item">

            <div class="fields">
              <div class="field">
                <%= link_to 'Limpar', pessoas_path, class: 'ui gray button' %>
                <%= f.submit 'Pesquisar', class: "ui blue button" %>
              </div>
            </div>
          <% end %>          
        </div>
      </div>

      <div class="ui divider"></div>

      <% if notice %>

        <div class="ui success message sucess_message">
          <div class="header">
            <i class="close icon" onclick="$('.sucess_message').hide()"></i>
            <%= notice %>
          </div>
        </div>

      <% end %>

      <% if alert %>

        <div class="ui error message error_message">
          <div class="header">
            <i class="close icon" onclick="$('.error_message').hide()"></i>
            <%= alert %>
          </div>
        </div>

      <% end %>

      <% if @users.count > 1 %>

        <% @users.each do |u| %>
          <div class="users_card <%= 'none' if u.email == current_user.email %>">
            <div class="users_card_image">
              <% if u.image.attached? %>
                <%= image_tag u.image, :size => "140x120" %>
              <% else %>
                <%= image_tag 'sem_foto', :size => "140x120" %>
              <% end %>
            </div>

            <div class="users_card_informations">
              <p class="users_card_nickname">
                <%= u.name %>
                <% if u.admin == true %>
                  ADM
                <% end %>
              </p>

              <p class="users_card_email"><%= u.email %></p>

              <div class="actions_perfil">
                <% if current_user.users.include? u %>
                  <%= link_to remote_follower_path(:user_email => u.email), data: { confirm: 'Deixar de seguir o usuário?' } do %>
                    <i class="user times icon remover_perfil"></i>
                  <% end %>
                <% else %>
                  <%= link_to add_new_follower_path(:user_email => u.email) do %>
                    <i class="user plus icon adicionar_perfil"></i>
                  <% end %>                  
                <% end %>

                <i class="eye icon olhar_perfil" onclick="$('.ui.modal.users_modal.<%= u.id %>').modal('show');"></i>
              </div>
            </div>
          </div>

          <div class="ui divider <%= 'none' if u.email == current_user.email %>"></div>

          <div class="ui modal email_modal">
            <i class="close icon" onclick="$('.ui.modal').modal('hide');"></i>

            <div class="header">
              Reportar usuário
            </div>

            <div class="content report_content_modal">

              <%= form_for @report, html: {class:"ui fluid form" } do |f| %>
                  <%= collection_select(:report, :motivation_id, Motivation.all, :id, :name, {:prompt => 'Escolha um motivo para o report', :multiple=>true }) %>

                  <br>

                  <%= collection_select(:report, :user_id, User.all, :id, :email, {:prompt => 'Escolha o usuário reportado para evitar erros de localização', :multiple=>true }) %>

                  <br>

                  <%= f.text_area :description, :placeholder => 'Descrição do report' %>

                  <div class="ui divider"></div>

                <%= f.submit "Enviar report", :class => 'ui positive button' %>
              <% end %>

            </div>
          </div>

          <div class="ui modal users_modal <%= u.id %>">
            <i class="close icon" onclick="$('.ui.modal').modal('hide');"></i>

            <div class="header">
              Dados de usuário
            </div>

            <div class="content users_content_modal">
              <div class="modal_image_user">
                <% if u.image.attached? %>
                  <%= image_tag u.image, :size => "140x120" %>
                <% else %>
                  <%= image_tag 'sem_foto', :size => "140x120" %>
                <% end %>

                <div class="ui divider width_30"></div>

                <div class="followers_and_follow">
                  <p class="ff">Seguindo: <%= u.users.count %></p>

                  <% teste = 0 %>

                  <% User.all.each do |teste_follow| %>
                    <% teste_follow.users.each do |other_user_follow| %>
                      <% teste = teste+1 if other_user_follow.id == u.id %>
                    <% end %>
                  <% end %>

                  <p class="ff">Seguidores: <%= teste %></p>                
                </div>
              </div>

              <div class="modal_informations_user">
                <h1>
                  <%= u.name %>
                  <% if u.admin == true %>
                   ADM
                  <% end %>
                </h1>

                <p><%= u.email %></p>

                <div class="ui divider"></div>

                <div class="age_and_phone">
                  <p><strong>Idade: </strong><%= u.age if u.age %></p>
                  <p><strong>Telefone: </strong><%= u.phone if u.phone %></p>
                </div>

                <p><strong>Endereço: </strong><%= u.address if u.address %></p>

                <p class="description_in_modal"><strong>Descrição: </strong><%= u.description if u.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h1>Nenhum usuário encontrado</h1>
        <div class="ui divider"></div>
      <% end %>

    </div>
  </div>
</div>