config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/logout' => 'devise/sessions#destroy'

    get '/login' => 'devise/sessions#new'
  end
  
  root 'pages#dashboard'

  get '/feed', to: 'pages#feed'
  get '/geral', to: 'pages#geral'  
  get '/pessoas', to: 'pages#pessoas'

  get '/user/add_new_follower' => 'users#add_new_follower', :as => :add_new_follower
  get '/user/remote_follower' => 'users#remote_follower', :as => :remote_follower

  get '/increment_deslike_geral' => 'publications#increment_deslike_geral', :as => :increment_deslike_g
  get '/increment_like_geral' => 'publications#increment_like_geral', :as => :increment_like_g
  get '/increment_deslike_feed' => 'publications#increment_deslike_feed', :as => :increment_deslike_f
  get '/increment_like_feed' => 'publications#increment_like_feed', :as => :increment_like_f

  resources :reports
  resources :notices
  resources :users
  resources :publications
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :motivation
  belongs_to :user
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @reports = Report.all
  end

  def show
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
  end

  def new
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @report = Report.new
  end

  def edit
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end
  end

  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to pessoas_path, notice: 'Você conseguiu efetuar o report com sucesso.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { redirect_to pessoas_path, alert: 'Você não conseguiu efetuar o report com sucesso.' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if user_signed_in?
      if current_user.admin == false
        redirect_to feed_path
      end
    end

    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:motivation_id, :user_id, :description)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true, html: {class:"ui fluid form" }) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="field">
    <%= form.label :motivation_id %>
    <%= form.text_field :motivation_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', :class => 'ui blue button' %>
  </div>

  <div class="ui divider"></div>

<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Motivation</th>
      <th>User</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.motivation.name %></td>
        <td><%= report.user.name %></td>
        <td><%= report.description %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Motivation:</strong>
  <%= @report.motivation_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @report.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report.description %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>